[versions]
kotlin = "1.6.10"
coroutines = "1.6.0"
compose = "1.1.0"
ktor = "1.6.7"
serialization = "1.3.2"
detekt = "1.20.0-RC1"
html = "0.7.3"
buildKonfig = "3.0.3"
versionUpdates = "0.42.0"
ftpUpload = "0.0.2"

[libraries]
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.3.2"
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

ktorCore = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktorNetty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktorSerial = { module = "io.ktor:ktor-serialization", version.ref = "ktor" }
ktorAuth = { module = "io.ktor:ktor-auth", version.ref = "ktor" }
ktorHtml = { module = "io.ktor:ktor-html-builder", version.ref = "ktor" }

ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientSerial = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktorClientLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClientOkHttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

ktorClientJs = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktorClientJsJson = { module = "io.ktor:ktor-client-json-js", version.ref = "ktor" }
ktorClientJsSerial = { module = "io.ktor:ktor-client-serialization-js", version.ref = "ktor" }

htmlJvm = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "html" }

logback = "ch.qos.logback:logback-classic:1.3.0-alpha14"

[bundles]
ktor = ["ktorCore", "ktorNetty", "ktorSerial", "ktorAuth", "ktorHtml", "htmlJvm"]

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
ftpupload = { id = "de.nilsdruyen.gradle-ftp-upload-plugin", version = "0.0.2" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}